changelog:
  exclude:
    labels:
      - skip-changelog
  categories:
    - title: New features
      labels: [feature, enhancement]
    - title: Fixes
      labels: [bug, fix]
    - title: Dependencies
      labels: [dependencies]
    - title: Other changes
      labels: ["*"]
